name: Generate Snake Animation
on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Game
        uses: Platane/snk@v3.1
        with:
          github_user_name: anirudddha  # Replace with your GitHub username
          outputs: dist/github-contribution-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Use the saved token

      - name: Upload to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
